### ISSUE TITLE
[Q] Which Role/Privileges are required to connect to the SRS?

### ISSUE THREAD

**Issue by lucdekens** [vmware/script-runtime-service-for-vsphere#12]
In other words, is it possible to connect and run script via for example a Read-Only account?
This would allow scripts that only retrieve data but make no changes.

**Comment by dmilov** [comment]
Every vSphere user can connect to SRS. SRS doesn't apply any role based access control. PowerCLI runtimes always connect the logged in user and scripts run against VC on behalf of this user.
