### ISSUE TITLE
Suspected typo in Pester test

### ISSUE THREAD

**Issue by lucdekens** [vmware/script-runtime-service-for-vsphere#14]
In the '_Runs CRUD10Datacenters PowerCLI Script_' Pester test in **PowerCLIScripts.Tests.ps1** there seems to be a typo in the 1st **It** statement (line 388).
The condition says it expects **20** entries, while the foreach loop in **CRUD10Datacenters.ps1** only goes to **10**.

**Comment by dmilov** [comment]
This is caused by the https://github.com/vmware/script-runtime-service-for-vsphere/issues/13.
Tests expects 10 x results from New-Datacenter plus 10 x results from Set-Datacenter

**Comment by dmilov** [comment]
Duplicate of #13
