### ISSUE TITLE
[Q] Can a user overwrite MaxRunspaceActiveTimeMinutes?

### ISSUE THREAD

**Issue by lucdekens** [vmware/script-runtime-service-for-vsphere#20]
It looks as if the current maximum time, specified in MaxRunspaceActiveTimeMinutes, a runspace can be active is 60 minutes.

Can this be overwritten for an existing SRS instance?
Or does it require a new SRS OVA build?

The reason for asking, a monitoring/collecting script that runs longer than 60 mins.

**Comment by dmilov** [comment]
Yes, SRS administrator is able to edit settings. In the development builds packaged in OVA the way to edit settings is as follows

1. Log in on the VM where SRS is running
2. Run the below command to open service settings for edit. Settings are opened as a json file in vim editor. Edit `MaxNumberOfRunspaces`, and `MaxRunspaceActiveTimeMinutes` values.

`kubectl edit configmap service-settings -n  script-runtime-service`

3. Save edits and exit. Settings are opened in vim editor by default, so save and exit command is `:wq!`

4. Settings should be updated automatically after certain period of time (~2min). You can force the settings reload by restarting the apigateway pod (the recommended way) with the below command

```
apigatewaypod=$(kubectl -n script-runtime-service get pod -l app=srs-apigateway -o  jsonpath={.items[0].metadata.name})
kubectl delete pod $apigatewaypod -n script-runtime-service
```
