### ISSUE TITLE
iso_url in photon-version.json returns 401

### ISSUE THREAD

**Issue by lucdekens** [vmware/script-runtime-service-for-vsphere#41]
The **iso_url** in the **photon-version.json** file in version 1.0 (http://dl.bintray.com/vmware/photon/3.0/GA/iso/photon-3.0-26156e2.iso) gives a 401 code.

**Comment by lucdekens** [comment]
When I change the URL to https://packages.vmware.com/photon/3.0/GA/iso/photon-3.0-26156e2.iso  it works

**Comment by dmilov** [comment]
Thanks Luc! Updating accordingly.

**Comment by lucdekens** [comment]
For info: in the Photon repo the corresponding issues is https://github.com/vmware/photon/issues/1074

**Comment by dmilov** [comment]
Switched to Photon OS 3.0 Update 3.0 and applied a fix that updates the repo URLs.
