### ISSUE TITLE
Build fails with Photon OS 3.0 Revision 3

### ISSUE THREAD

**Issue by lucdekens** [vmware/script-runtime-service-for-vsphere#45]
During the build the **SRS_Application** fails to get the **photon-kickstart.json** file.
With Photon OS 3.0 Revision 2 it works without an issue.

It looks as if with Photon OS 3.0 Revision 3 the retries to get the photon-kickstart.json are not done.
After one try, the Photon installer stops.

![Snag_35d62f9f](https://user-images.githubusercontent.com/7760649/102699721-4143b680-4247-11eb-865d-8ef8d388f715.png)

With Photon OS 3.0 Revision 2 the installer tries 5 times to get the photon-kickstart.json file.

This seems to be the same issue as reported in https://github.com/vmware/photon/issues/1065

**Comment by cloudmaniac** [comment]
Hi Luc, I was able to make it work by changing slightly the kickstart file, see my comment [there](https://github.com/vmware/photon/issues/1065#issuecomment-756437643). My new kickstart file: [photon-kickstart.json](https://github.com/cloudmaniac/packer-templates/blob/master/photon/http/photon-kickstart.json).

**Comment by lucdekens** [comment]
Thanks for that @cloudmaniac , but implementing this solution would minimally require a change in the logic of the SRS builder.
I'm not sure at this point in time if we are looking at a timing issue in the Photon kickstarter logic.

I would have preferred a reply from the Photon Team on your Photon issue https://github.com/vmware/photon/issues/1065
