### ISSUE TITLE
error Kubernetes cluster unreachable installing on new ovf

### ISSUE THREAD

**Issue by pargit** [vmware/script-runtime-service-for-vsphere#64]
### Describe the bug

hi,
i deployed a new vm from the ovf.
i have configured network, dns record and hostname, and updated the hosts file with the new name.
when running the command 
helm install ~/srs --generate-name --set vc.address='10.xx.xx.20' --set vc.user='xxx@vsphere.local' --set vc.password='xxxx' --set srs.service.hostname='vko-srs1.xxx' --set vc.tls_thumbprint='c98837971d0yyyyyya9e2f9xxxxxxxxxe060361d3a' 
i get the following error:
Error: Kubernetes cluster unreachable: an error on the server ("") has prevented the request from succeeding

i tried using ip as the srs server name, i hadded the fqdn to the hosts file but nothing seems to help.
i have dns resolving from both vc to srs and vice versa.

what am i missing?

### Reproduction steps

```bash
1. deploy ovf
2. set ip/dns/hostname
3. update hosts file
4. run the command from the wiki
...
```

### Expected behavior

srs installed correctly

**Comment by dmilov** [comment]
@pargit is the error produced by the `help install` command?

**Comment by pargit** [comment]
> 

yes. i wrote the command i'm running (same as in the wiki with my parameters)

**Comment by dmilov** [comment]
@pargit Do you mind contacting me on slack to chat about it?
https://github.com/vmware/script-runtime-service-for-vsphere#join-us-on-slack

**Comment by dmilov** [comment]
The certificates of the Kubernetes cluster on the SRS Host VM have expired. It will need rebuild and republish.

**Comment by dmilov** [comment]
I updated the release binaries with updated SRS Host VM.

**Comment by dmilov** [comment]
The update Host VM OVF is failing. There is a k8s cluster networking resource issue that prevents kuberentes node to get prepared
`kubectl get node`
```
NAME                 STATUS     ROLES    AGE    VERSION
kind-control-plane   NotReady   master   6d7h   v1.18.2
```

**Comment by dmilov** [comment]
@kamennikolov if someone from the team wants to jump and help with that one as it needs more investigation. I cannot spend much time digging into it right now. There is an ongoing discussion about it on the slack channel as well.

**Comment by dmilov** [comment]
It turned out the default RAM and CPU of the SRS Host VM were not enough to run the kind cluster node. Updated the OVF with new defaults.
